### ISSUE TITLE
How to increase YuMi's movement speed

### ISSUE THREAD

**Issue by Miya-imslab** [bhomaidan1990/yumi_egm_driver#2]
Hello. - Hello.
I am using ROS Melodic to run YuMi, but when I try to run the actual device, I don't know what the law is to make YuMi move faster.
Is it possible to change (increase) the speed by changing the value of [joint_limits.yaml](https://github.com/bhomaidan1990/yumi_egm_driver/blob/main/yumi/yumi_moveit_config/config/joint_limits.yaml) in this repository?
I would appreciate it if you could tell me.

**Comment by bhomaidan1990** [comment]
Hi @sleepysummer as this issue is not related to this repo, please see the original abb driver repo for this detail: [ ABB YuMi increase speed #37 ](https://github.com/ros-industrial/abb_robot_driver/issues/37)
