### ISSUE TITLE
Questions about moveit_planning_execution.launch

### ISSUE THREAD

**Issue by Miya-imslab** [bhomaidan1990/yumi_egm_driver#3]
Hello. - Hello.
I am trying to run YuMi in a ros melodic environment with the packages in this repository.

However, when I run `roslaunch yumi_moveit_config moveit_planning_execution.launch`, I get the following warning message and Rviz does not show the correct status of YuMi.

> [ WARN] [1667803439.959102225]: Group state 'Calib' doesn't specify all group joints in group 'both_arms'. gripper_l_joint, gripper_r_joint are missing.
[ WARN] [1667803439.959186655]: Group state 'Calib_left' doesn't specify all group joints in group 'left_arm'. gripper_l_joint is missing.
[ WARN] [1667803439.959200388]: Group state 'Calib_right' doesn't specify all group joints in group 'right_arm'. gripper_r_joint is missing.
[ WARN] [1667803440.221413175]: Configured default soft limits for 'yumi_robr_joint_1': position [-2.91147; 2.91147], k: 1
[ WARN] [1667803440.222513392]: Configured default soft limits for 'yumi_robr_joint_2': position [-2.4795; 0.751626], k: 1
[ WARN] [1667803440.223560629]: Configured default soft limits for 'yumi_robr_joint_3': position [-2.91147; 2.91147], k: 1
[ WARN] [1667803440.224597963]: Configured default soft limits for 'yumi_robr_joint_4': position [-2.13393; 1.3823], k: 1
[ WARN] [1667803440.225633876]: Configured default soft limits for 'yumi_robr_joint_5': position [-5.01084; 5.01084], k: 1
[ WARN] [1667803440.226685070]: Configured default soft limits for 'yumi_robr_joint_6': position [-1.52053; 2.38446], k: 1
[ WARN] [1667803440.227725420]: Configured default soft limits for 'yumi_robr_joint_7': position [-3.95683; 3.95683], k: 1
[ WARN] [1667803440.228765328]: Configured default soft limits for 'yumi_robl_joint_1': position [-2.91147; 2.91147], k: 1
[ WARN] [1667803440.229811880]: Configured default soft limits for 'yumi_robl_joint_2': position [-2.4795; 0.751626], k: 1
[ WARN] [1667803440.230861688]: Configured default soft limits for 'yumi_robl_joint_3': position [-2.91147; 2.91147], k: 1
[ WARN] [1667803440.231901381]: Configured default soft limits for 'yumi_robl_joint_4': position [-2.13393; 1.3823], k: 1
[ WARN] [1667803440.232938480]: Configured default soft limits for 'yumi_robl_joint_5': position [-5.01084; 5.01084], k: 1
[ WARN] [1667803440.233978709]: Configured default soft limits for 'yumi_robl_joint_6': position [-1.52053; 2.38446], k: 1
[ WARN] [1667803440.235023507]: Configured default soft limits for 'yumi_robl_joint_7': position [-3.95683; 3.95683], k: 1

I am not familiar with ROS, so any specific solution would be appreciated.

**Comment by bhomaidan1990** [comment]
@sleepysummer the packages in this repository are for test purpose only, and no support is granted.
